services:
  auth:
    image: ${REGISTRY_PATH}/mc_auth:latest
    build:
      context: ./src/auth
      dockerfile: Dockerfile
  chat:
    image: ${REGISTRY_PATH}/mc_chat:latest
    build:
      context: ./src/chat
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_healthy
  db:
    image: ${REGISTRY_PATH}/mc_db:latest
    build:
      context: ./src/db
      dockerfile: Dockerfile
      args:
        password: ${MSSQL_SA_PASSWORD}
    environment:
      - ACCEPT_EULA=Y
