services:
  auth:
    image: mc_auth
    build:
      context: ./src/auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  chat:
    image: mc_chat
    build:
      context: ./src/chat
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_healthy
  db:
    image: mc_db
    build:
      context: ./src/db
      dockerfile: Dockerfile
      args:
        password: ${MSSQL_SA_PASSWORD}
    environment:
      - ACCEPT_EULA=Y
