services:

  https-proxy:
    image: ${REGISTRY_PATH:-localhost}/mc_http-proxy:latest
    build:
      context: ./src/http-proxy
      dockerfile: Dockerfile
      args:
        CHAT_DOMAIN: ${CHAT_DOMAIN:-localhost}
        CHAT_MODULE_ADDRESS: ${CHAT_MODULE_ADDRESS:-chat:8080}
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  chat:
    image: ${REGISTRY_PATH:-localhost}/mc_chat:latest
    build:
      context: ./src/chat
      dockerfile: Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - IS_PRODUCTION=${IS_PRODUCTION:-false}
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_started
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock

  db:
    image: ${REGISTRY_PATH:-localhost}/mc_db:latest
    build:
      context: ./src/db
      dockerfile: Dockerfile
      args:
        password: ${MSSQL_SA_PASSWORD}
    environment:
      - ACCEPT_EULA=Y
  auth:
    image: ${REGISTRY_PATH:-localhost}/mc_auth:latest
    build:
      context: ./src/auth
      dockerfile: Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

volumes:
  caddy_data:
  caddy_config:
