name: Build and Deploy to ACR

on:
  push:
    branches:
      - main
    
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.REGISTRY_PATH }}

      - name: Build Docker Image
        run: docker compose build --no-cache
        env:
          REGISTRY_PATH: ${{ secrets.REGISTRY_PATH }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
          IS_PRODUCTION: true
          CHAT_DOMAIN: ${{ secrets.DNS_NAME_LABEL }}.${{ secrets.AZURE_LOCATION }}.azurecontainer.io
          CHAT_MODULE_ADDRESS: http://localhost:8080

      - name: Push Docker Image
        run: docker compose push
        env:
          REGISTRY_PATH: ${{ secrets.REGISTRY_PATH }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
          IS_PRODUCTION: true

      - name: Deploy to Azure Container Instances   
        run: az container create --resource-group ChatGroup --file aci.yaml
        env:
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          REGISTRY_PATH: ${{ secrets.REGISTRY_PATH }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          DNS_NAME_LABEL: ${{ secrets.DNS_NAME_LABEL }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}