name: Run Tests
on:
  [push, pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Running tests for auth module.
        run: |
          cd src/auth/
          mvn --batch-mode --update-snapshots verify
          cd ../..
        env:
          MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
      - name: Running tests for chat module.
        run: |
          cd src/chat/
          mvn --batch-mode --update-snapshots verify
        env:
          MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
